modLoader="javafml"
loaderVersion="[47,)"
license="GNU LGPLv3"

[[mods]]
    modId="pelagic_prehistory"
    version="20.1.0.0"
    displayName="Pelagic Prehistory"
    authors="skyjay1, MapleMoose"
    credits="Definitely Dilo, Jade, Listine, SennaHN, Traut"
    description='''Did someone say Cambrian Explosion?'''

[[dependencies.pelagic_prehistory]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pelagic_prehistory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pelagic_prehistory]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pelagic_prehistory]]
    modId="unusualprehistory"
    mandatory=false
    versionRange="[1.5.0,)"
    ordering="AFTER"
    side="BOTH"